export const GET_MENTORS = 'GET_MENTORS';
export const GET_MENTORS_REQUEST = 'GET_MENTORS_REQUEST';
export const GET_MENTORS_SUCCESS = 'GET_MENTORS_SUCCESS';
export const GET_MENTORS_FAILED = 'GET_MENTORS_FAILED';